
import javax.swing.JOptionPane; // Para poder usar el JOptionPane

public class RectanguloIU extends javax.swing.JFrame {

    /**
     * Creates new form RectanguloIU
     */
    // Miembro agregado
    Rectangulo rec;
    
    public RectanguloIU() {
        initComponents();
        
        // Agregadando objetos
        rec = new Rectangulo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dimensionesFrame = new javax.swing.JPanel();
        anchoFrame = new javax.swing.JPanel();
        anchoL = new javax.swing.JLabel();
        anchoTL = new javax.swing.JTextField();
        anchoFrame1 = new javax.swing.JPanel();
        altoL = new javax.swing.JLabel();
        altoTL = new javax.swing.JTextField();
        calcularB = new javax.swing.JToggleButton();
        dimensionesFrame1 = new javax.swing.JPanel();
        anchoFrame2 = new javax.swing.JPanel();
        areaL = new javax.swing.JLabel();
        areaTL = new javax.swing.JTextField();
        anchoFrame3 = new javax.swing.JPanel();
        altoL1 = new javax.swing.JLabel();
        perimetroTL = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        dimensionesFrame.setBorder(javax.swing.BorderFactory.createTitledBorder("Dimensiones"));

        anchoL.setText("Ancho");

        anchoTL.setBackground(new java.awt.Color(255, 255, 255));
        anchoTL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anchoTLActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout anchoFrameLayout = new javax.swing.GroupLayout(anchoFrame);
        anchoFrame.setLayout(anchoFrameLayout);
        anchoFrameLayout.setHorizontalGroup(
            anchoFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(anchoFrameLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(anchoL)
                .addGap(47, 47, 47)
                .addComponent(anchoTL, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12))
        );
        anchoFrameLayout.setVerticalGroup(
            anchoFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, anchoFrameLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(anchoFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(anchoTL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(anchoL))
                .addGap(12, 12, 12))
        );

        altoL.setText("Alto");

        altoTL.setBackground(new java.awt.Color(255, 255, 255));
        altoTL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                altoTLActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout anchoFrame1Layout = new javax.swing.GroupLayout(anchoFrame1);
        anchoFrame1.setLayout(anchoFrame1Layout);
        anchoFrame1Layout.setHorizontalGroup(
            anchoFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(anchoFrame1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(altoL)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(altoTL, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12))
        );
        anchoFrame1Layout.setVerticalGroup(
            anchoFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, anchoFrame1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(anchoFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(altoTL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(altoL))
                .addGap(12, 12, 12))
        );

        calcularB.setText("Calcular");
        calcularB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calcularBActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout dimensionesFrameLayout = new javax.swing.GroupLayout(dimensionesFrame);
        dimensionesFrame.setLayout(dimensionesFrameLayout);
        dimensionesFrameLayout.setHorizontalGroup(
            dimensionesFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dimensionesFrameLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dimensionesFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(anchoFrame, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(anchoFrame1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(calcularB))
                .addContainerGap())
        );
        dimensionesFrameLayout.setVerticalGroup(
            dimensionesFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dimensionesFrameLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(anchoFrame, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(anchoFrame1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(calcularB)
                .addContainerGap(96, Short.MAX_VALUE))
        );

        dimensionesFrame1.setBorder(javax.swing.BorderFactory.createTitledBorder("Calculos"));

        areaL.setText("Area");

        areaTL.setBackground(new java.awt.Color(255, 255, 255));
        areaTL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                areaTLActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout anchoFrame2Layout = new javax.swing.GroupLayout(anchoFrame2);
        anchoFrame2.setLayout(anchoFrame2Layout);
        anchoFrame2Layout.setHorizontalGroup(
            anchoFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(anchoFrame2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(areaL)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(areaTL, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12))
        );
        anchoFrame2Layout.setVerticalGroup(
            anchoFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, anchoFrame2Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(anchoFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(areaTL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(areaL))
                .addGap(12, 12, 12))
        );

        altoL1.setText("Perimetro");

        perimetroTL.setBackground(new java.awt.Color(255, 255, 255));
        perimetroTL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                perimetroTLActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout anchoFrame3Layout = new javax.swing.GroupLayout(anchoFrame3);
        anchoFrame3.setLayout(anchoFrame3Layout);
        anchoFrame3Layout.setHorizontalGroup(
            anchoFrame3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(anchoFrame3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(altoL1)
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(perimetroTL, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        anchoFrame3Layout.setVerticalGroup(
            anchoFrame3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, anchoFrame3Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(anchoFrame3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(perimetroTL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(altoL1))
                .addGap(12, 12, 12))
        );

        javax.swing.GroupLayout dimensionesFrame1Layout = new javax.swing.GroupLayout(dimensionesFrame1);
        dimensionesFrame1.setLayout(dimensionesFrame1Layout);
        dimensionesFrame1Layout.setHorizontalGroup(
            dimensionesFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dimensionesFrame1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dimensionesFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(anchoFrame2, javax.swing.GroupLayout.Alignment.CENTER, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(anchoFrame3, javax.swing.GroupLayout.Alignment.CENTER, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        dimensionesFrame1Layout.setVerticalGroup(
            dimensionesFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dimensionesFrame1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(anchoFrame2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(anchoFrame3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(dimensionesFrame, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dimensionesFrame1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(dimensionesFrame, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(dimensionesFrame1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void anchoTLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anchoTLActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_anchoTLActionPerformed

    private void altoTLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_altoTLActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_altoTLActionPerformed

    private void calcularBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calcularBActionPerformed
        // TODO add your handling code here:
        System.out.println("Calculando area");
        double area, perimetro;
        if(anchoTL.getText().isEmpty() || altoTL.getText().isEmpty()) {
            // System.out.println("Ingrese datos para hacer los calculos");
            JOptionPane.showMessageDialog(null, "Por favor ingresar los datos \npara hacer los calculos", 
                    "ERROR", JOptionPane.ERROR_MESSAGE);
        }
        else {
            rec.setBase(Double.parseDouble(anchoTL.getText()));
            rec.setAltura(Double.parseDouble(altoTL.getText()));
            area = rec.calcularArea();
            perimetro = rec.calcularPerimetro();
            areaTL.setText(Double.toString(area));
            perimetroTL.setText(Double.toString(perimetro));
        }
    }//GEN-LAST:event_calcularBActionPerformed

    private void perimetroTLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_perimetroTLActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_perimetroTLActionPerformed

    private void areaTLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_areaTLActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_areaTLActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RectanguloIU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RectanguloIU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RectanguloIU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RectanguloIU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RectanguloIU().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel altoL;
    private javax.swing.JLabel altoL1;
    private javax.swing.JTextField altoTL;
    private javax.swing.JPanel anchoFrame;
    private javax.swing.JPanel anchoFrame1;
    private javax.swing.JPanel anchoFrame2;
    private javax.swing.JPanel anchoFrame3;
    private javax.swing.JLabel anchoL;
    private javax.swing.JTextField anchoTL;
    private javax.swing.JLabel areaL;
    private javax.swing.JTextField areaTL;
    private javax.swing.JToggleButton calcularB;
    private javax.swing.JPanel dimensionesFrame;
    private javax.swing.JPanel dimensionesFrame1;
    private javax.swing.JTextField perimetroTL;
    // End of variables declaration//GEN-END:variables
}
